name: hello-world

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions repo
        uses: actions/checkout@v5

      - name: Hello World
        run: echo "Hello World!"
        
      - name: check files
        run: ls -ltrh