name: Dragon Cow

on: push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions repo
        uses: actions/checkout@v5

      - name: script
        run: |
            chmod u+x dragoncow.sh
            ./dragoncow.sh
      - name: Archive  artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DRAGON
          path: dragoncow.txt
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: download  artifacts
        uses: actions/download-artifact@v4
        with:
          name: DRAGON

      - name: test dragon 
        run: grep 'Dragon'  dragoncow.txt
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Deploy shit 
        run: echo "Deploy..........."