name: Dragon Cow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions repo
        uses: actions/checkout@v5

      - name: script
        run: ./dragoncow.sh