name: Dragon Cow

on: push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions repo
        uses: actions/checkout@v5

      - name: script
        run: |
            chmod u+x dragoncow.sh
            ./dragoncow.sh
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: test dragon 
        run: grep 'Dragon'  dragoncow.txt
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Deploy shit 
        run: echo "Deploy..........."